### ISSUE TITLE
1.14.4 Generation Issues

### ISSUE THREAD

**Issue by robert-beckley** [BentoBoxWorld/SkyGrid#22]
**Description**
The generation does not work. And the clean super flat flag just turns is self off right way without doing anything.
The spawn chunks are fine but as soon as you go out from spawn its flat land. 

**Expected behaviour**
The generator is set to bento box and new chunks are made in the grid format, not a flatland 
world name is lowercase as bento box likes 

**Screenshots**
![image](https://user-images.githubusercontent.com/41904721/61989597-888b3f00-b075-11e9-8c38-34a115096a80.png)
![image](https://user-images.githubusercontent.com/41904721/61989640-06e7e100-b076-11e9-9783-3b69292817bf.png)

**Server Information:**

[Please complete the following information:]
 - Database being used JSON
 - Java Version: 8
![image](https://user-images.githubusercontent.com/41904721/61989600-a193f000-b075-11e9-842d-10056b5fbf66.png)
![image](https://user-images.githubusercontent.com/41904721/61989603-aeb0df00-b075-11e9-829e-f185407c4696.png)

**Additional context**

[configs.zip](https://github.com/BentoBoxWorld/SkyGrid/files/3437822/configs.zip)

Ping me on discord @Robert#1017 for discussion

**Comment by tastybento** [comment]
Hi @robert-beckley  - I'm not sure why you're getting the Superflat. I can't replicate that right now. However, I fixed the clean super turning off problem. I recommend you try the latest BentoBox and latest SkyGrid because there are significant fixes in both that you should pick up.

**Comment by robert-beckley** [comment]
I will pick up latest builds of code mc tonight and see how it goes for 24
hours

**Comment by robert-beckley** [comment]
Okay using these builds 
![image](https://user-images.githubusercontent.com/41904721/62003348-2efc4080-b159-11e9-8075-38af74f686e1.png)
 everything seems a lot better. But when it makes the chunk it block updates and now everything is flowing lava/water 
![image](https://user-images.githubusercontent.com/41904721/62003351-476c5b00-b159-11e9-9a76-f4e9b5e6794a.png)
![image](https://user-images.githubusercontent.com/41904721/62003353-4a674b80-b159-11e9-89d0-1fb8e0eb40fc.png)

Will let it run for a while and see if anything odd happens but this is very good progress

**Comment by robert-beckley** [comment]
Update: Chests are spawning empty in new chunks

**Comment by tastybento** [comment]
Hi Robert,

Can you teleport somewhere way far away from the other chunks and see if the chunks spawn correctly for you? Ie there is no mention of chunk regeneration in the log? I’m concerned that we haven’t fixed the root cause which is that the chunks are not being generated from scratch correctly. 
The fix Superflat is only supposed to be a worst case helper to fix when Superflat accidentally is generated for some reason and shouldn’t occur generally. 
I’ll check into the chests and physics and see why that’s happening.

**Comment by tastybento** [comment]
I had a look at your error log and you are getting warnings of large chunk sizes. These come from the server. I’m on my phone right now so I can’t check your confit. Did you change any config for SkyGrid like the height of the blocks?

**Comment by tastybento** [comment]
Okay, I fixed the chests being empty and the water/lava flowing. That's in the latest BentoBox build. 

I had a look at your config though and your height is 240 blocks - that will cause the "large chunk" errors you are seeing. I never knew this was an issue but chunks can only be up to a certain size normally. This used to be an exploit where someone could make a book with pages full of Chinese characters and put lots of them in chests and it would crash the server. Spigot and Paper "fixed" this by storing these super-sized chunks differently but maybe SkyGrid is crapping these out somehow and that's why you see the Superflat. I'd recommend reducing the block height to 128 and see if that's the root cause of the Superflat being generated.

**Comment by robert-beckley** [comment]
Okay Update 1/2, Chests are now being generated with loot. The block updates are not happening. the only issue now is that the items are being dropped as it cycles through the blocks. This is something I can live with but it will make lag on many servers from all the entities. overall time per chunk regen is down also. 
It still takes a few passes to get all the chunks even when loaded but how it is now is functioning well I am yet to check new "fresh" chunks and will let you know. 
![image](https://user-images.githubusercontent.com/41904721/62020271-aab3c700-b205-11e9-8608-04f721a83977.png)
![image](https://user-images.githubusercontent.com/41904721/62020273-adaeb780-b205-11e9-8c99-4fba1e55b02e.png)

**Comment by robert-beckley** [comment]
I don't think it is generating Fresh chunks it's more making a super flat then converting it fast I TPed  far out (/tppos 10000000 65 10000000) and this is my result 
![image](https://user-images.githubusercontent.com/41904721/62020800-c15b1d80-b207-11e9-9c3e-cf65a85c504b.png)
I then turned off super flat cleaner and teleported to the negative of that location (/tppos -10000000 65 -10000000) and its all super flat 

As for the large chunks yeah there is a duplication glitch with cramming the chest so the file size is too big and won't save. BUT I am getting that issue in sky block since updated and skyblock will not genera islands currently. (will be a new issue for that soon)
https://www.youtube.com/watch?v=sd8SM8YWP9U&t=2s

**Comment by tastybento** [comment]
What version of Paper are you using?

**Comment by robert-beckley** [comment]
![image](https://user-images.githubusercontent.com/41904721/62036808-da7ac300-b235-11e9-9bba-8c9e84688e4f.png)
